@ First battle
Text_NinjaBoyIntro1:
	.string "So you've met me, your mortal\n"
	.string "enemy. Prepare for the slaughter!$"

Text_NinjaBoyDefeated1:
	.string "T-this, can't be! You will pay!$"

Text_NinjaBoyTrack1:
	.string "I will keep my eyes close on you.\n"
	.string "Never let your guard down!$"

@ Second battle
Text_NinjaBoyIntro2:
	.string "Here we come again, you and me.\n"
	.string "Now, strike me fierce!$"

Text_NinjaBoyDefeated2:
	.string "You have such wonderful power.$"

Text_NinjaBoyTrack2:
	.string "I begin to respect you, I will learn\n"
	.string "from you to become a greater trainer.$"

@ Third battle
Text_NinjaBoyIntro3:
	.string "Placeholder.$"

Text_NinjaBoyDefeated3:
	.string "Placeholder.$"

Text_NinjaBoyTrack3:
	.string "Placeholder.$"

@ Fourth battle
Text_NinjaBoyIntro4:
	.string "Placeholder.$"

Text_NinjaBoyDefeated4:
	.string "Placeholder.$"

Text_NinjaBoyTrack4:
	.string "Placeholder.$"
