UndergroundTunnels_Text_DebrisOnTheWayClearIt:
	.string "There's debris on the way and a\n"
	.string "faint light overhead. Want to go?$"

UndergroundTunnels_Text_DebrisOnTheWayCannotAdvance:
	.string "There's a lot of debris on the way.\n"
    .string "Cannot advance further.$"

UndergroundTunnels_Text_TooMuchDebris:
	.string "There's too much debris in the way.$"

UndergroundTunnels_Text_EnterCave:
	.string "There's a lot of debris in the way.\n"
	.string "Do you want to enter?$"
