NinjaBoy_Battle1::
	trainerbattle_single TRAINER_NINJABOY_1, Text_NinjaBoyIntro1, Text_NinjaBoyDefeated1, NinjaBoyTrack1
    msgbox Text_NinjaBoyTrack1, MSGBOX_AUTOCLOSE
	end

NinjaBoyTrack1::
    setninjaflags FLAG_NINJA_BOY2
    msgbox Text_NinjaBoyTrack1, MSGBOX_AUTOCLOSE
    end

NinjaBoy_Battle2::
	trainerbattle_single TRAINER_NINJABOY_2, Text_NinjaBoyIntro2, Text_NinjaBoyDefeated2, NinjaBoyTrack2
    msgbox Text_NinjaBoyTrack2, MSGBOX_AUTOCLOSE
	end

NinjaBoyTrack2::
	setninjaflags FLAG_NINJA_BOY3
    msgbox Text_NinjaBoyTrack2, MSGBOX_AUTOCLOSE
    end

NinjaBoy_Battle3::
	trainerbattle_single TRAINER_NINJABOY_3, Text_NinjaBoyIntro3, Text_NinjaBoyDefeated3, NinjaBoyTrack3
    msgbox Text_NinjaBoyTrack3, MSGBOX_AUTOCLOSE
	end

NinjaBoyTrack3::
	setninjaflags FLAG_NINJA_BOY4
    msgbox Text_NinjaBoyTrack3, MSGBOX_AUTOCLOSE
    end

NinjaBoy_Battle4::
	trainerbattle_single TRAINER_NINJABOY_4, Text_NinjaBoyIntro4, Text_NinjaBoyDefeated4, NinjaBoyTrack4
    msgbox Text_NinjaBoyTrack4, MSGBOX_AUTOCLOSE
	end

NinjaBoyTrack4::
	setninjaflags FLAG_NINJA_BOY5
    msgbox Text_NinjaBoyTrack4, MSGBOX_AUTOCLOSE
    end
